package by.epam.like_it.common_util;

public enum  CommandName {

    LOAD_MAIN, LOGINATION, REGISTRATION, LOG_OUT, CHANGE_LANGUAGE,

    SEARCH_POST, SEARCH_POSTS_BY_CONSTRICTION,
    SEARCH_POSTS_BY_ADD_CONSTRICTION, SEARCH_POSTS_BY_ORDER,

    VIEW_POSTS_LIST,VIEW_SINGLE_POST,
    VIEW_SINGLE_USER,

    TOGGLE_RATING_CLIENT, TOGGLE_FAVORITE_CLIENT,

    CREATE_COMMENT_AUTH, CREATE_POST_AUTH, CREATE_ANSWER_AUTH,

    BAN_COMMENT_RESPONSIBLE, BAN_POST_RESPONSIBLE, BAN_USER_RESPONSIBLE, BAN_RATING_RESPONSIBLE,
    BAN_ANSWER_RESPONSIBLE,

    LOAD_ENTITY_AUTH, LOAD_SUBSCRIBING_CLIENT, LOAD_FAVORITE_POSTS_CLIENT,

    EDIT_COMMENT_OWNER, EDIT_ANSWER_OWNER, EDIT_POST_OWNER,
    EDIT_PHOTO_AUTH, EDIT_PROFILE_AUTH,
    EDIT_SETTINGS_AUTH, EDIT_SUBSCRIBING_CLIENT,

    DELETE_PHOTO_AUTH,
    CREATE_FAVORITE_CLIENT, DELETE_FAVORITE_CLIENT;
}
